print("Name an animal:")
animal = input()
print("Name a present verb:")
verb = input()
print("Name a planet:")
planet = input()
print("The" , animal + " had secret powers and went" , verb + " on" , planet + " plotting against the evil squirrel union.")